// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package swapiGraphQLGo

type Person struct {
	Name      string  `json:"name"`
	Height    string  `json:"height"`
	Mass      string  `json:"mass"`
	HairColor string  `json:"hair_color"`
	SkinColor string  `json:"skin_color"`
	EyeColor  string  `json:"eye_color"`
	BirthYear string  `json:"birth_year"`
	Gender    string  `json:"gender"`
	Homeworld *Planet `json:"homeworld"`
	Created   int     `json:"created"`
	Edited    int     `json:"edited"`
}

type PersonInput struct {
	ID string `json:"id"`
}

type Planet struct {
	Name           string `json:"name"`
	RotationPeriod string `json:"rotation_period"`
	OrbitalPeriod  string `json:"orbital_period"`
	Diameter       string `json:"diameter"`
	Climate        string `json:"climate"`
	Gravity        string `json:"gravity"`
	Terrain        string `json:"terrain"`
	SurfaceWater   string `json:"surface_water"`
	Population     string `json:"population"`
	Created        int    `json:"created"`
	Edited         int    `json:"edited"`
}
